services:
  backend:
    build: backend/
    environment:
      MYSQL_HOST: db
      MYSQL_USER: testing
      MYSQL_PASSWORD: AlbedoScope123
      MYSQL_DB: blog
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - blog_network

  frontend:
    build: .
    ports:
      - "5173:5173"
    networks:
      - blog_network
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: AlbedoScope123
    ports:
      - "3307:3306"
    networks:
      - blog_network
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      

networks:
  blog_network:
    driver: bridge
