services:
  backend:
    build: backend/
    environment:
      MYSQL_HOST: db
      MYSQL_USER: testing
      MYSQL_PASSWORD: AlbedoScope123
      MYSQL_DB: blog
      #MYSQL_PORT: 3307
    ports:
      - "8080:80"
  web:
    build: .
    ports:
      - "5173:5173"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: superDuperSecurePasswd
      MYSQL_DATABASE: blog
      MYSQL_USER: testing
      MYSQL_PASSWORD: AlbedoScope123
    ports:
      - "3307:3306"
    volumes:
      - ./sql/blog_backup.sql:/var/lib/mysqld
