services:
  backend:
    build: backend/
    environment:
      MYSQL_HOST: db
      MYSQL_USER: testing
      MYSQL_PASSWORD: AlbedoScope123
      MYSQL_DB: blog
      MYSQL_PORT: 3306
    ports:
      - "8080:80"
  web:
    build: .
    ports:
      - "5173:5173"
  db:
    image: mysql:latest
    volumes:
      - ./sql/backup/blog_backup.sql:/docker-entrypoint-initdb.d/blog.sql
    environment:
      MYSQL_ROOT_PASSWORD: RootJaumePC1.
      MYSQL_DATABASE: blog
      MYSQL_USER: testing
      MYSQL_PASSWORD: AlbedoScope123
    ports:
      - "3306:3306"
